### ISSUE TITLE
Feature request: Day AND time based import

### ISSUE THREAD

**Issue by boravsbora** [infernoboy/fitbit-importer#1]
Hello,

First off, thank you for putting this together. It's exactly what I have been looking for!

Would it be possible to extend the shortcut to import from a specific day AND between a specific time range on that day? So, as an example, I would love to be able to import data from say Monday between the hours of 3:00pm and 4:00pm?

Thanks for considering this.
/B

**Comment by infernoboy** [comment]
Thanks for using it! The way importing works is by sending a request to the Fitbit API for specific day, which doesn't allow for selecting times. While it's technically possible to filter the entries once the data is downloaded, it would require a bit of a rewrite and potentially slow the shortcut down a lot when dealing with the thousands of entries Fitbit will return. I don't think I'll be implementing it, sorry.
